/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   aggregate_sym.c                                    :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: ariard <ariard@student.42.fr>              +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2017/02/09 17:39:18 by ariard            #+#    #+#             */
/*   Updated: 2017/02/13 22:59:11 by ariard           ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "parser.h"

t_aggrematch		g_aggrematch[] =
{
	{TK_WORD, CMD_SUFFIX, CMD_SUFFIX, ALL, 0},
	{TK_WORD, TK_PIPE, PATTERN, ALL, 0},
	{TK_WORD, WORDLIST, WORDLIST, ALL, 0},
	{TK_ASSIGNEMENT_WORD, CMD_PREFIX,CMD_PREFIX, ALL, 0},
	{TK_FI, ELSE_PART, IF_CLAUSE, ALL, IF},
	{TK_FI, COMPOUND_LIST, IF_CLAUSE, ALL, IF},
	{TK_DONE, COMPOUND_LIST, DO_GROUP, ALL, DO},
//Esac ?
	{TK_ESAC, CASE_LIST, CASE_CLAUSE, ALL, TK_CASE},
	{TK_ESAC, CASE_LIST_NS, CASE_CLAUSE, ALL, TK_CASE},
	{TK_ESAC, LINEBREAK, CASE_CLAUSE, ALL, TK_CASE},
	{TK_RBRACE, COMPOUND_LIST, BRACE_GROUP, ALL, TK_LBRACE},
	{TK_PAREN_CLOSE, COMPOUND_LIST, SUBSHELL, ALL, TK_PAREN_OPEN},	
//watch this
	{SEPARATOR, COMPOUND_LIST, COMPOUND_LIST, ALL, 0},
	{LINEBREAK, SEPARATOR_OP, SEPARATOR, ALL, SEPARATOR_OP},
	{LINEBREAK, TK_SEMI, SEQUENTIAL_SEP, ALL, TK_SEMI},
	{LINEBREAK, TK_PAREN_CLOSE, TK_ESAC, CASE_ITEM_NS, PATTERN_CASE},
	{LINEBREAK, TK_PAREN_CLOSE, FUNC, ALL, FNAME},
	{LINEBREAK, TK_DSEMI, CASE_ITEM, ALL, PATTERN_CASE},
	{LINEBREAK, COMPLETE_COMMANDS, PROGRAM, ALL, LINEBREAK},
	{LINEBREAK, TK_PIPE, PIPE_SEMI_SEQUENCE, ALL, PIPE_SEQUENCE},
	{LINEBREAK, COMPLETE_COMMANDS, PROGRAM, ALL, LINEBREAK}, 
	{NEWLINE_LIST, NEWLINE_LIST, NEWLINE_LIST, ALL, NEWLINE},
	{NEWLINE_LIST, NAME, SEQUENTIAL_SEP, ALL, 0},
	{NEWLINE_LIST, IN, SEQUENTIAL_SEP, ALL, 0},
	{NEWLINE_LIST, WORDLIST, SEQUENTIAL_SEP, ALL, 0},
	{NEWLINE_LIST, TERM, SEPARATOR, ALL, 0},
	{NEWLINE_LIST, COMPOUND_LIST, SEPARATOR, ALL, 0},
	{IO_HERE, ALL, IO_REDIRECT, ALL, TK_IO_NUMBER},
	{FILENAME, TK_LESS, IO_FILE, ALL, TK_LESS},
	{FILENAME, TK_LESSAND, IO_FILE, ALL, TK_LESSAND},
	{FILENAME, TK_GREAT, IO_FILE, ALL, TK_GREAT},
	{FILENAME, TK_GREATAND, IO_FILE, ALL, TK_GREATAND},
	{FILENAME, TK_DGREAT, IO_FILE, ALL, TK_DGREAT},
	{FILENAME, TK_LESSGREAT, IO_FILE, ALL, TK_LESSGREAT},
	{FILENAME, TK_CLOBBER, IO_FILE, ALL, TK_CLOBBER},
	{IO_FILE, ALL, IO_REDIRECT, ALL, TK_IO_NUMBER},
	{IO_REDIRECT, COMPOUND_COMMAND, REDIRECT_LIST, ALL, REDIRECT_LIST},
	{IO_REDIRECT, CMD_SUFFIX, CMD_SUFFIX, ALL, CMD_SUFFIX},
	{IO_REDIRECT, CMD_NAME, CMD_SUFFIX, ALL, 0},
	{IO_REDIRECT, CMD_WORD, CMD_SUFFIX, ALL, 0},
	{IO_REDIRECT, CMD_PREFIX, CMD_PREFIX, ALL, CMD_PREFIX},
	{IO_REDIRECT, LINEBREAK, CMD_PREFIX, ALL, 0},
	{IO_REDIRECT, TK_BANG, CMD_PREFIX, ALL, 0},
	{IO_REDIRECT, SEPARATOR_OP, CMD_PREFIX, ALL, 0},
	{IO_REDIRECT, NEWLINE_LIST, CMD_PREFIX, ALL, 0},
	{REDIRECT_LIST, COMPOUND_COMMAND, COMPOUND_COMMAND, ALL, COMPOUND_COMMAND},
	{CMD_SUFFIX, CMD_WORD, SIMPLE_COMMAND, ALL, CMD_PREFIX},
	{CMD_SUFFIX, CMD_NAME, SIMPLE_COMMAND, ALL, CMD_NAME},
	{CMD_PREFIX, LINEBREAK, SIMPLE_COMMAND, ALL_SEPARATOR, 0},
	{CMD_PREFIX, TK_BANG, SIMPLE_COMMAND, ALL_SEPARATOR, 0},
	{CMD_PREFIX, SEPARATOR_OP, SIMPLE_COMMAND, ALL_SEPARATOR, 0},
	{CMD_PREFIX, NEWLINE_LIST, SIMPLE_COMMAND, ALL_SEPARATOR, 0},
	{CMD_WORD, CMD_PREFIX, SIMPLE_COMMAND, ALL_SEPARATOR, CMD_PREFIX},
//to check	
	{CMD_NAME, LINEBREAK, SIMPLE_COMMAND, ALL, 0},
	{CMD_NAME, TK_BANG, SIMPLE_COMMAND, ALL, 0},
	{CMD_NAME, SEPARATOR_OP, SIMPLE_COMMAND, ALL, 0},
	{CMD_NAME, NEWLINE_LIST, SIMPLE_COMMAND, ALL, 0},
	{CMD_NAME, PIPE_SEMI_SEQUENCE, SIMPLE_COMMAND, ALL, 0},

	{SIMPLE_COMMAND, ALL, COMMAND, ALL, 0},
	{DO_GROUP, NAME, FOR_CLAUSE, ALL, TK_FOR},
	{DO_GROUP, SEQUENTIAL_SEP, FOR_CLAUSE, ALL, TK_FOR},
	{DO_GROUP, COMPOUND_LIST, LOOP, ALL, COMPOUND_LIST},
	{LOOP, WHILE, WHILE_CLAUSE, ALL, WHILE},
	{LOOP, TK_UNTIL, UNTIL_CLAUSE, ALL, TK_UNTIL},
	{BRACE_GROUP, ALL, COMPOUND_COMMAND, ALL, 0},
	{FUNCTION_BODY, FUNC, FUNCTION_DEFINITION, ALL, 0},
	{FUNCTION_DEFINITION, ALL, COMMAND, ALL, 0},
	{UNTIL_CLAUSE, ALL, COMPOUND_COMMAND, ALL, 0},
	{WHILE_CLAUSE, ALL, COMPOUND_COMMAND, ALL, 0},
	{ELSE_PART, COMPOUND_LIST, ELSE_PART, ALL, TK_ELIF},
	{IF_CLAUSE, ALL, COMPOUND_COMMAND, ALL, 0},
	{CASE_ITEM, CASE_LIST, CASE_LIST, ALL, CASE_LIST},
	{CASE_ITEM, LINEBREAK, CASE_LIST, ALL, CASE_LIST},
	{CASE_ITEM_NS, CASE_LIST, CASE_LIST_NS, ALL, CASE_LIST},
	{CASE_ITEM_NS, LINEBREAK, CASE_LIST_NS, ALL, CASE_LIST},
	{CASE_CLAUSE, ALL, COMPOUND_COMMAND, ALL, 0},
	{FOR_CLAUSE, ALL, COMPOUND_COMMAND, ALL, 0},
	{TERM, LINEBREAK, COMPOUND_LIST, ALL, LINEBREAK},
	{COMPOUND_LIST, TK_ELSE, ELSE_PART, ALL, TK_ELSE},
	{COMPOUND_LIST, TK_THEN, ELSE_PART, ALL, TK_ELIF},
	{SUBSHELL, ALL, COMPOUND_COMMAND, ALL, 0},
	{COMPOUND_COMMAND, ALL, COMMAND, ALL, 0},
	{COMMAND, PIPE_SEMI_SEQUENCE, PIPE_SEQUENCE, ALL, PIPE_SEMI_SEQUENCE},
	{COMMAND, TK_BANG, PIPE_SEQUENCE, ALL, 0},
	{COMMAND, SEPARATOR_OP, PIPE_SEQUENCE, ALL, 0},
	{COMMAND, NEWLINE_LIST, PIPE_SEQUENCE, ALL, 0},
	{COMMAND, LINEBREAK, PIPE_SEQUENCE, ALL, 0},
	{PIPE_SEQUENCE, TK_BANG, PIPELINE, ALL, TK_BANG},
	{PIPE_SEQUENCE, SEPARATOR_OP, PIPELINE, ALL, 0},
	{PIPE_SEQUENCE, NEWLINE_LIST, PIPELINE, ALL, 0},
	{PIPE_SEQUENCE, LINEBREAK, PIPELINE, ALL_SEPARATOR, 0},
	{PIPELINE, LINEBREAK, AND_OR, ALL, 0},
//	{PIPELINE, LINEBREAK, AND_OR, ALL, AND_OR},
	{PIPELINE, SEPARATOR_OP, AND_OR, ALL, 0},
	{AND_OR, SEPARATOR_OP, LIST, ALL, LIST},
	{AND_OR, NEWLINE_LIST, LIST, ALL, 0},
	{AND_OR, LINEBREAK, LIST, ALL, 0},
	{LIST, NEWLINE_LIST, COMPLETE_COMMAND, ALL, 0},
	{LIST, LINEBREAK, COMPLETE_COMMAND, ALL, 0},
	{COMPLETE_COMMAND, NEWLINE_LIST, COMPLETE_COMMANDS, ALL, COMPLETE_COMMANDS},
	{COMPLETE_COMMAND, LINEBREAK, COMPLETE_COMMANDS, ALL, 0},
//	voir decoupe separateur au lexer 
	{COMPLETE_COMMANDS, LINEBREAK, PROGRAM, ALL_SEPARATOR, 0},
	{0, 0, 0, 0, 0},
};

int			aggregate_sym(t_sym **stack, t_sym *new_sym, 
			t_parstate *state, t_list *next_token)
{
	int		i;
	int		next;
	t_token	*token;

	i = 0;
	next = 0;
	if (next_token)
		if ((token = next_token->content))
			next = token->type;
	DG("aggregate head %s && sym %s && next %s", 
	read_state(**stack), read_state(*new_sym), read_state(next));
	while (g_aggrematch[i].top)
	{
		if (*new_sym == g_aggrematch[i].top && (**stack == g_aggrematch[i].under
			|| g_aggrematch[i].under == ALL 
			|| g_aggrematch[i].under == ALL_SEPARATOR)
			&& (next == g_aggrematch[i].next_token || next == 0 
			|| g_aggrematch[i].next_token == ALL 
			|| (g_aggrematch[i].next_token == ALL_SEPARATOR && next == TK_SEMI)))
		{
			DG("MATCH : %s", read_state(g_aggrematch[i].new_sym));
			*new_sym = g_aggrematch[i].new_sym;
			if (g_aggrematch[i].erase_sym)
			{
				pop_stack(stack, g_aggrematch[i].erase_sym);
				DG("stack after pop: %s", read_state(**stack));
			}
			if (eval_sym(**stack, *new_sym))
				return ((*state = ERROR));
			aggregate_sym(stack, new_sym, state, next_token);
			return (0);
		}
		i++;
	}
	return (0);
}
